a    *            ADD
a    scsi         SKP

ap   *            ADD
d    *            ADD
e    *            ADD
f    *            ADD
i    *            ADD
iv   *            ADD
n    *            ADD
oop  *            ADD
q    *            SKP
t    *            ADD
tcl  *            ADD
x    *            ADD
xap  *            ADD
xd   *            ADD
xv   *            ADD
y    *            ADD
