#! /bin/sh
#
# rc.inet1	This shell script boots up the base INET system.
#
# Version:	@(#)/etc/rc.d/rc.inet1	1.01	05/27/93
#

HOSTNAME=`hostname`

# Attach the loopback device.
/etc/ifconfig lo 127.0.0.1
/etc/route add 127.0.0.1

# qemu user network config
/etc/ifconfig eth0 10.0.2.101 netmask 255.255.255.0 broadcast 10.0.2.255 up
/etc/route add 10.0.2.0 eth0
/etc/route add default gw 10.0.2.2
