a    *            ADD
ap   *            ADD
d    *            ADD
e    *            ADD
f    *            ADD
l    *            ADD
n    *            ADD
t    *            ADD
tcl  *            ADD
x    *            ADD
xap  *            ADD
y    *            ADD
