#!/bin/sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
if [ ! -r $T_PX/vmlinuz ]; then
 if [ -r /cdrom/kernels/scsi.s/bzImage ]; then
  cp -a /cdrom/kernels/scsi.s/bzImage $T_PX/vmlinuz
  chmod 400 $T_PX/vmlinuz
  rdev -R $T_PX/vmlinuz 1
  rdev $T_PX/vmlinuz $ROOT_DEVICE
  rdev -r $T_PX/vmlinuz 0
  cp -a /cdrom/kernels/scsi.s/System.map $T_PX/boot/System.map
  cp -a /cdrom/kernels/scsi.s/config $T_PX/boot/config
 fi
fi
