[qemu]
profile = "linux-1.2"

[download]
cdrom = "infomagic/ldr/1996_09"

[extract]
source = "disc2.iso"
boot_image = "images/1213/boot0015.img"
extra_images = ["images/rescue.img", "images/ramdisk1.img", "images/ramdisk2.img"]
truncate = ["boot0015.img"]

[install]
driver = "redhat-dialog"
variant = "3.0.3"

[install.packages]
package_series = [
    "Applications",
    # "DOS Compatibility",
    "Development",
    # "Development Libraries",
    "Documentation",
    # "Emacs",
    "Games",
    # "Mail",
    "Multimedia Programs",
    # "Network Admin",
    "Networking",
    # "Networking Servers",
    # "Other Programming Languages",
    # "Other Shells",
    # "Printing",
    # "Serial Communications",
    # "Tcl-Tk Extensions",
    # "TeX",
    "X Applications",
    "X Development",
    "X Games",
    "X Windows",
    # "XView",
    # "a.out compatitibility",
    # "Other",
]

[install.accounts]
root_password = "password"
# user = "redhat"
# user_home = true

[install.locale]
hardware_clock = "utc"
timezone = "UTC"
keymap = "us.map"

[postinst]
stages = ["x11"]
