EXTRACT_SOURCE=disc1.iso
EXTRACT_BOOT_IMAGE=distributions/slakinst/boot144/bare
EXTRACT_ROOT_IMAGE=distributions/slakinst/root144/color144
EXTRACT_PACKAGES=distributions/slackware
extract_install_files
