[qemu]
profile = "linux-1.0"

[qemu.network]
device = "ne2k_isa,iobase=0x280"

[download]
slackware_mirror = "1.1.2"

[extract]
boot_image = "slackware-1.1.2/bootdisk/1_44meg/bareboot.gz"
root_image = "slackware-1.1.2/bootdisk/1_44meg/color144.gz"
package_source = "slackware-1.1.2"
boot_link = "bareboot"
root_link = "color144"
decompress = ["bareboot.gz", "color144.gz"]

[install]
driver = "slackware-dialog"
variant = "1.1.2"

[install.packages]
source = "/dev/hdb1"
tagfile_path = false

[postinst]
stages = ["tty", "x11"]
