#!/bin/sh
T_PX="`cat /tmp/SeTT_PX`"
rm -f /tmp/SeTmount /tmp/SeTDS /tmp/SeTCDdev
dialog --title "Install from the Slackware CD-ROM" \
--menu "\
You should be able to install directly from the Slackware \
CD-ROM if you have one of the drive types listed below.  (If \
this doesn't work for some reason, you can still install by \
copying the a1...y1 directories to your hard drive and \
installing from there, or by making floppy disks under DOS) \
If your CD-ROM drive uses an ATAPI or IDE interface (see the \
manual) then use option (1) even if you recognize the brand \
name of your drive further down the list. \
What type of CD-ROM drive do you have?" \
20 70 6 \
"1" "Works with most ATAPI/IDE CD drives (/dev/hd*)" \
"2" "SCSI (/dev/scd0 or /dev/scd1)" \
"3" "Sony CDU31A/CDU33A (/dev/sonycd)" \
"4" "Sony 531/535 (/dev/cdu535)" \
"5" "Mitsumi (proprietary interface, not IDE) (/dev/mcd)" \
"6" "New Mitsumi (also not IDE) (/dev/mcdx0)" \
"7" "Sound Blaster Pro/Panasonic (/dev/sbpcd)" \
"8" "Aztech/Orchid/Okano/Wearnes (/dev/aztcd)" \
"9" "Phillips and some ProAudioSpectrum16 (/dev/cm206cd)" \
"10" "Goldstar R420 (/dev/gscd)" \
"11" "Optics Storage 8000 (/dev/optcd)" \
"12" "Sanyo CDR-H94 + ISP16 soundcard (/dev/sjcd)" \
"scan" "Try to scan for your CD drive" \
2> /tmp/cdtype
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/tmpmsg /tmp/cdtype
 exit
fi
CD_ROM_TYPE="`cat /tmp/cdtype`"
rm -f /tmp/tmpmsg /tmp/cdtype
if [ "$CD_ROM_TYPE" = "scan" ]; then
  for device in /dev/scd0 /dev/scd1 /dev/sonycd /dev/cdu535 /dev/mcd \
/dev/sbpcd /dev/aztcd /dev/hdd /dev/hdc /dev/hdb /dev/hda \
/dev/hde /dev/hdf /dev/hdg /dev/hdh \
/dev/cm206cd /dev/gscd0 /dev/mcdx0 /dev/mcdx1 \
/dev/optcd0 /dev/sjcd ; do
   dialog --infobox "Scanning $device..." 3 30
   mount -o ro -t iso9660 $device /var/adm/mount 1> /dev/null 2> /dev/null
   if [ $? = 0 ]; then
    DRIVE_FOUND=$device
    break
   fi
  done
  umount /var/adm/mount 1> /dev/null 2> /dev/null
  if [ "$DRIVE_FOUND" = "" ]; then
   dialog --title "DRIVE NOT FOUND" --msgbox \
"A CD-ROM drive could not be found on any of the devices that were \
scanned. Make sure you're using the bootdisk that contains the \
drivers that support your CD drive. Please consult the BOOTING file \
for more information on \
forcing the detection of your drive, and then reattempt installation. \
If all else fails, see the FAQ.TXT for information about copying \
parts of this CD to your DOS partition to allow you to install." \
12 65
  else
   dialog --title "CD-ROM DRIVE DETECTED SUCCESSFULLY" --msgbox \
"A CD-ROM drive was found on device $DRIVE_FOUND." 5 65
   CD_DEVICE="$DRIVE_FOUND"
  fi
elif [ "$CD_ROM_TYPE" = "2" ]; then
 dialog --title "SELECT SCSI DEVICE" --menu "\
Which SCSI CD-ROM are you using? (If you're not sure, \n\
select /dev/scd0)" 10 60 2 \
"/dev/scd0" "SCSI CD 0" \
"/dev/scd1" "SCSI CD 1" 2> /tmp/whichscsi
 if [ $? = 1 -o $? = 255 ]; then
  rm -f /tmp/tmpmsg /tmp/cdtype /tmp/whichscsi
  exit
 fi
 CD_DEVICE="`cat /tmp/whichscsi`"
 rm -f /tmp/whichscsi
elif [ "$CD_ROM_TYPE" = "3" ]; then
 CD_DEVICE="/dev/sonycd"
elif [ "$CD_ROM_TYPE" = "4" ]; then
 CD_DEVICE="/dev/cdu535"
elif [ "$CD_ROM_TYPE" = "5" ]; then
 CD_DEVICE="/dev/mcd"
elif [ "$CD_ROM_TYPE" = "6" ]; then
 CD_DEVICE="/dev/mcdx0"
elif [ "$CD_ROM_TYPE" = "7" ]; then
 CD_DEVICE="/dev/sbpcd"
elif [ "$CD_ROM_TYPE" = "8" ]; then
 CD_DEVICE="/dev/aztcd"
elif [ "$CD_ROM_TYPE" = "9" ]; then
 CD_DEVICE="/dev/cm206cd"
elif [ "$CD_ROM_TYPE" = "10" ]; then
 CD_DEVICE="/dev/gscd"
elif [ "$CD_ROM_TYPE" = "11" ]; then
 CD_DEVICE="/dev/optcd"
elif [ "$CD_ROM_TYPE" = "12" ]; then
 CD_DEVICE="/dev/sjcd"
elif [ "$CD_ROM_TYPE" = "1" ]; then
 dialog --title "SELECT IDE DEVICE" --menu \
"Which IDE device is your CD-ROM drive connected to? \
If you're not sure, we can try to \
scan for your drive." \
17 70 9 \
"scan" "Try to scan for your drive" \
"/dev/hda" "Primary IDE interface, drive 1" \
"/dev/hdb" "Primary IDE interface, drive 2" \
"/dev/hdc" "Secondary IDE interface, drive 1" \
"/dev/hdd" "Secondary IDE interface, drive 2" \
"/dev/hde" "Third IDE interface, drive 1" \
"/dev/hdf" "Third IDE interface, drive 2" \
"/dev/hdg" "Fourth IDE interface, drive 1" \
"/dev/hdh" "Fourth IDE interface, drive 2" \
2> /tmp/idecd
 if [ ! "`cat /tmp/idecd`" = "scan" ]; then
  CD_DEVICE="`cat /tmp/idecd`"
 else
  for device in /dev/hdd /dev/hdc /dev/hdb /dev/hda \
/dev/hde /dev/hdf /dev/hdg /dev/hdh ; do
   dialog --infobox "Scanning $device..." 3 30
   mount -o ro -t iso9660 $device /var/adm/mount 1> /dev/null 2> /dev/null
   if [ $? = 0 ]; then
    DRIVE_FOUND=$device
    break
   fi
  done
  umount /var/adm/mount 1> /dev/null 2> /dev/null
  if [ "$DRIVE_FOUND" = "" ]; then
   dialog --title "DRIVE NOT FOUND" --msgbox \
"An IDE CD-ROM drive could not be found on any of the devices that were \
scanned.  Please consult the BOOTING file for more information on \
forcing the detection of your drive, and then reattempt installation. \
If all else fails, see the SLAKWARE.FAQ for information about copying \
parts of this CD to your DOS partition to allow you to install." \
12 55
  else
   dialog --title "IDE CD-ROM DRIVE DETECTED SUCCESSFULLY" --msgbox \
"An IDE CD-ROM drive was found on device $DRIVE_FOUND." 5 65
   CD_DEVICE="$DRIVE_FOUND"
  fi
 fi
fi
# The CD will be mounted automatically later on:
# echo "$CD_DEVICE       /cdrom        iso9660       ro   1   1" > /tmp/SeTcdfstab

while [ 0 ] ; do
 dialog --title "Pick your installation method" --menu "\
 You can run most of the system from the Slackware CD-ROM \
 if you're short of drive space or if you just want to test Linux without \
 going through a complete installation. \
 If you're new to this, PLEASE read \
 the help file before you make your selection. \
 Which option would you like?" 15 74 4 \
 "help" "Read the installation method help file" \
 "slakware" "Normal installation to hard drive" \
 "slaktest" "Link /usr -> /cdrom/live/usr to run mostly from CD" \
 "custom" "Install from a custom directory" \
 2> /tmp/SeTreturn
 if [ $? = 1 -o $? = 255 ]; then
  rm -f /tmp/cdtype /tmp/SeTreturn
  exit
 fi
 if [ "`cat /tmp/SeTreturn`" = "help" ]; then
  dialog --title "INSTALLATION METHOD HELP" --textbox /usr/lib/setup/IMhelp \
  20 74
  continue
 fi
 break
done

SLACK_SOURCE_LOCATION="`cat /tmp/SeTreturn`"

if [ "$SLACK_SOURCE_LOCATION" = "custom" ]; then
 dialog --title "SELECT CUSTOM SOURCE DIRECTORY" --inputbox "Now we need \
 to know \
 which directory on the CD contains the Slackware sources.  This location \
 may vary depending on the CD you have. You may omit the leading '/' if \
 you like.  What directory are the Slackware sources in?" 11 67 \
 2> /tmp/slacksource
 if [ $? = 1 -o $? = 255 ]; then
  rm -f /tmp/cdtype /tmp/slacksource
  exit
 fi
 rm -f /tmp/tmpmsg
 SLACK_SOURCE_LOCATION="`cat /tmp/slacksource`"
 rm -f /tmp/slacksource
fi

while [ 0 ]; do
 mount -o ro -t iso9660 $CD_DEVICE /var/adm/mount 1> /dev/null 2> /dev/null
 if [ ! $? = 0 ]; then
  dialog --title "MOUNT ERROR" --menu "There was an error attempting to mount the CD-ROM device." \
11 60 3 \
"1" "Abort CD installation" \
"2" "Attempt to mount the CD-ROM device again" \
"3" "Ignore the error and continue" 2> /tmp/errordo
  if [ $? = 1 -o $? = 255 ]; then
   rm -f /tmp/SeTDS /tmp/SeTmount /tmp/SeTCDdev /tmp/errordo
   exit;
  fi
  DOWHAT="`cat /tmp/errordo`"
  rm -f /tmp/errordo
  if [ $DOWHAT = 1 ]; then
   rm -f /tmp/SeTDS /tmp/SeTmount /tmp/SeTCDdev
   exit;
  elif [ $DOWHAT = 3 ]; then
   break;
  fi
 else
  if [ ! -d /var/adm/mount/$SLACK_SOURCE_LOCATION ]; then
   dialog --title "ERROR: DIRECTORY NOT FOUND" --msgbox "The Slackware source directory could not be found. You'll \
have to reconfigure your source media before you can install." 8 60
    rm -f /tmp/SeTmount /tmp/SeTDS /tmp/SeTCDdev   
   exit
  fi
  break;
 fi
done

# since we've mounted successfully, let's refresh the link:
if [ ! -d $T_PX/dev ]; then
 mkdir $T_PX/dev
 chown root.root $T_PX/dev
 chmod 755 $T_PX/dev
fi
( cd $T_PX/dev ; ln -sf $CD_DEVICE cdrom )
echo "/var/adm/mount/$SLACK_SOURCE_LOCATION" > /tmp/SeTDS
echo "-source_mounted" > /tmp/SeTmount
echo "$CD_DEVICE" > /tmp/SeTCDdev
echo "/dev/null" > /tmp/SeTsource
