#!/bin/sh
# Copyright 1993, Patrick Volkerding, Moorhead, MN.
# Use and redistribution covered by the same terms as the "setup" script.
if [ ! -d /usr/lib/kbd/keytables ]; then
 dialog --title "Required files are missing" --msgbox "You cannot remap your keyboard until you install the \
package 'keymaps.tgz' on disk A3. It contains the keyboard map files \
required to proceed." 9 40
 exit
fi

while [ 0 ]; do
dialog --title "KEYBOARD MAP SELECTION" --menu "You may select one \
of the following keyboard maps. Use the UP/DOWN arrow keys to scroll \
through the whole list of choices." \
20 68 12 \
"azerty.map" "" \
"be-latin1.map" "" \
"cf.map" "" \
"de-latin1-nodeadkeys.map" "" \
"de-latin1.map" "" \
"de.map" "" \
"defkeymap.map" "" \
"defkeymap_V1.0.map" "" \
"dk-latin1.map" "" \
"dk.map" "" \
"dvorak.map" "" \
"emacs.map" "" \
"emacs2.map" "" \
"es.map" "" \
"fi-latin1.map" "" \
"fi.map" "" \
"fr-latin1.map" "" \
"fr.map" "" \
"gr-pc.map" "" \
"gr.map" "" \
"hebrew.map" "" \
"it-ibm.map" "" \
"it.map" "" \
"no-latin1.map" "" \
"no.map" "" \
"pl.map" "" \
"ru.map" "" \
"ru1.map" "" \
"ru2.map" "" \
"sf-latin1.map" "" \
"sf.map" "" \
"sg-latin1-lk450.map" "" \
"sg-latin1.map" "" \
"sg.map" "" \
"slovene.map" "" \
"uk.map" "" \
"us.map" "" \
 2> /tmp/keymp
 if [ ! $? = 0 ]; then
  rm -f /tmp/keymp /tmp/keyscript
  exit;
 fi
 MAPNAME="`cat /tmp/keymp`"
 mv /tmp/keymp /tmp/SeTkeymap

 loadgzkeys $MAPNAME 1> /dev/null 2> /dev/null

 while [ 0 ]; do
  dialog --title "KEYBOARD TEST" --inputbox \
"\n\
OK, the new map is now installed. You may now test it by typing\n\
anything you want. To quit testing the keyboard, enter [1] on a\n\
line by itself to accept the map and go on, or [2] on a line by\n\
itself to reject the current keyboard map and select a new one. " 13 70 2> /tmp/keytest
  if [ $? = 1 ]; then
   REPLY="n"
   break;
  fi
  REPLY="`cat /tmp/keytest`"
  rm -f /tmp/keytest
  if [ "$REPLY" = "1" -o "$REPLY" = "2" ]; then
   break;
  fi
 done
 if [ "$REPLY" = "1" ]; then
  break;
 else
  rm -f /tmp/`cat /tmp/SeTkeymap`
  rm -f /tmp/SeTkeym*
  continue;
 fi
done
