[qemu]
profile = "linux-1.0"

[download]
cdrom = "infomagic/ldr/1993_12"

[[download.files]]
path = "x_svga.tgz"
url = "https://mirrors.slackware.com/slackware/slackware-1.1.2/x2/x_svga.tgz"

[extract]
source = "disc1.iso"
boot_image = "sunsite/distributions/slackware/bootdisk/1_44meg/uniboot"
package_source = "sunsite/distributions/slackware"

[[extract.overlays]]
source = "x_svga.tgz"
destination = "fat/packages/x2/x_svga.tgz"

[install]
driver = "slackware-tty"

[install.packages]
package_sets = "A AP D E F IV N TCL OI OOP X XAP XD XV Y"

[install.network]
hostname = "darkstar"
domain = "retro.net"
ip = "10.0.2.15"
network = "10.0.2.0"
gateway = "10.0.2.2"
netmask = "255.255.255.0"
broadcast = "10.0.2.255"
nameserver = "10.0.2.3"

[install.locale]
timezone = "US/Central"

[postinst]
stages = ["tty", "x11"]
