# Declarative configuration for the Python retro host.

[[download.files]]
path = "disc1.iso"
url = "https://archive.org/download/InfomagicLinuxDevelopersResourceApril1996/ldr0496_1.iso"

[[download.files]]
path = "disc2.iso"
url = "https://archive.org/download/InfomagicLinuxDevelopersResourceApril1996/ldr0496_2.iso"

[[download.files]]
path = "disc3.iso"
url = "https://archive.org/download/InfomagicLinuxDevelopersResourceApril1996/ldr0496_3.iso"

[[download.files]]
path = "disc4.iso"
url = "https://archive.org/download/InfomagicLinuxDevelopersResourceApril1996/ldr0496_4.iso"

[[download.files]]
path = "disc5.iso"
url = "https://archive.org/download/InfomagicLinuxDevelopersResourceApril1996/ldr0496_5.iso"

[[download.files]]
path = "disc6.iso"
url = "https://archive.org/download/InfomagicLinuxDevelopersResourceApril1996/ldr0496_6.iso"

