[qemu]
profile = "linux-2.4"

[download]
cdrom = "kimmel/slackware/8.1"

[extract]
source = "disc1.iso"

[install]
driver = "slackware-dialog"
variant = "8.0-9.0"

[install.prompts]
postinst_prompt = "root@darkstar:~#"

[postinst]
stages = ["tty", "x11"]
