DEBIAN_BASE_TARBALL=base1_3.tgz
DEBIAN_PREPARE_FUNCTION=prepare_base_system_dinstall
DEBIAN_INITTAB_FALLBACK=etc/init.d/inittab
DEBIAN_ROOT_HOOK=.bash_profile
DEBIAN_ROOT_TARBALL=/etc/root.sh.tar.gz
DEBIAN_TAR_EXTRACTOR="star -x"
DEBIAN_INSTALL_BOOT_FLOPPY=1
DEBIAN_INSTALL_DRIVERS=1
DEBIAN_CONFIGURE_MODULES=1
DEBIAN_GUARD_ETH0=1
DEBIAN_SKIP_SETUP_SH=1

. "$SOURCEMOUNT/autoinst.d/debian/baseinst/dinstall.sh"
