#!/bin/sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
T_PX="`cat $TMP/SeTT_PX`"
rm -f $TMP/SeTSERIES
dialog --title "PACKAGE SERIES SELECTION" --checklist \
"Now it's time to select which general categories of software \
to install on your system. \
Use the spacebar to select or unselect the software you wish to \
install. \
You can use the up and down arrows to see all the possible choices. \
Recommended choices have been preselected. \
Press the ENTER key when you are finished." \
20 75 9 \
"A" "Base Linux system" on \
"AP" "Various Applications that do not need X" on \
"D" "Program Development (C, C++, Lisp, Perl, etc.)" on \
"E" "GNU Emacs" on \
"F" "FAQ lists, HOWTO documentation" on \
"GTK" "GTK+ and GNOME programs for X" on \
"K" "Linux kernel source" on \
"KDE" "Qt and the K Desktop Environment for X" on \
"N" "Networking (TCP/IP, UUCP, Mail, News)" on \
"T" "TeX typesetting software" on \
"TCL" "Tcl/Tk script languages" on \
"X" "XFree86 X Window System" on \
"XAP" "X Applications" on \
"XV" "XView (OpenLook Window Manager, apps)" on \
"Y" "Games (that do not require X)" on 2> $TMP/series
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/series
 exit
fi
INSTSETS="`cat $TMP/series | tr -d " "`"
INSTSETS="`echo $INSTSETS | tr "\042" "#" `"
INSTSETS="`echo $INSTSETS | tr "," "#" `"
rm -f $TMP/series
echo "$INSTSETS" > $TMP/SeTSERIES
