[qemu]
profile = "linux-2.0"

[qemu.network]
device = "ne2k_isa"

[install]
driver = "slackware-dialog"
variant = "3.1-3.4"

[postinst]
stages = ["modules", "tty", "x11"]

[postinst.modules]
enable = "ne io=0x300"
