# installer for pkgtool-based Slackware versions

normalize_sets() {
  SETS=`echo $SETS | sed 's/[ ;,]/#/g'`
}

move_setup_hook() {
  if [ -f "$TARGETMOUNT/$1" ]; then
    if [ ! -d "$TARGETMOUNT/$SLACK_ADM_DIR/setup/install" ]; then
      mkdir -p "$TARGETMOUNT/$SLACK_ADM_DIR/setup/install"
    fi
    mv "$TARGETMOUNT/$1" "$TARGETMOUNT/$SLACK_ADM_DIR/setup/install"
  fi
}

copy_setup_binaries() {
  if [ ! -r "$TARGETMOUNT/sbin/pkgtool" -a -r "$SLACK_PKGTOOL_SOURCE" ]; then
    cp "$SLACK_PKGTOOL_SOURCE" "$TARGETMOUNT/sbin/pkgtool"
  fi
  if [ ! -r "$TARGETMOUNT/sbin/setup" -a -r "$SLACK_SETUP_SOURCE" ]; then
    cp "$SLACK_SETUP_SOURCE" "$TARGETMOUNT/sbin/setup"
  fi
  if [ -r "$TARGETMOUNT/sbin/pkgtool" ]; then
    chmod 755 "$TARGETMOUNT/sbin/pkgtool"
  fi
  if [ -r "$TARGETMOUNT/sbin/setup" ]; then
    chmod 755 "$TARGETMOUNT/sbin/setup"
  fi
}

install_pkgtool_sets() {
  echo "### installing packages..."
  normalize_sets
  "$SLACK_PKGTOOL_SOURCE" -source_mounted -ignore_tagfiles -source_dir $SOURCEMOUNT -target_dir $TARGETMOUNT -sets "#$SETS#"
}

write_rootdev() {
  if [ ! -d "$TARGETMOUNT/etc/rc.d" ]; then
    mkdir -p "$TARGETMOUNT/etc/rc.d"
  fi
  if [ ! -r "$TARGETMOUNT/etc/rc.d/ROOTDEV" ]; then
    echo "$ROOTDEV" > "$TARGETMOUNT/etc/rc.d/ROOTDEV"
    chmod 644 "$TARGETMOUNT/etc/rc.d/ROOTDEV"
  fi
}

install_fstab() {
  if [ ! -r "$TARGETMOUNT/etc/fstab" -a -r "$TARGETMOUNT/fstab.tmp" ]; then
    mv "$TARGETMOUNT/fstab.tmp" "$TARGETMOUNT/etc/fstab"
    chmod 644 "$TARGETMOUNT/etc/fstab"
  fi
  if [ -r "$TARGETMOUNT/etc/fstab" ]; then
    fgrep "/proc" "$TARGETMOUNT/etc/fstab" >/dev/null 2>&1
    if [ ! $? = 0 ]; then
      echo "none        /proc        proc        defaults" >> "$TARGETMOUNT/etc/fstab"
      echo " " >> "$TARGETMOUNT/etc/fstab"
    fi
  fi
}

fix_permissions() {
  echo "### fixing permissions..."
  ( cd $TARGETMOUNT ; chmod 755 ./ )
  if [ -d "$TARGETMOUNT/var" ]; then
    ( cd $TARGETMOUNT ; chmod 755 ./var )
  fi
  if [ -d "$TARGETMOUNT/usr/src/linux" ]; then
    chmod 755 "$TARGETMOUNT/usr/src/linux"
  fi
  if [ ! -d "$TARGETMOUNT/proc" ]; then
    mkdir "$TARGETMOUNT/proc"
    chown root.root "$TARGETMOUNT/proc"
  fi
  if [ ! -L "$TARGETMOUNT/lib/cpp" ]; then
    ( cd $TARGETMOUNT/lib ; ln -sf /usr/lib/gcc-lib/i486-linux/*.*.*/cpp cpp )
  fi
  if [ ! -d "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucp" ]; then
    mkdir -p "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucp"
  fi
  chown uucp.uucp "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucp"
  chmod 1777 "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucp"
  if [ ! -d "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucppublic" ]; then
    mkdir -p "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucppublic"
  fi
  chown uucp.uucp "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucppublic"
  chmod 1777 "$TARGETMOUNT/$SLACK_SPOOL_DIR/uucppublic"
  chmod 1777 "$TARGETMOUNT/tmp"
  if [ ! -d "$TARGETMOUNT/$SLACK_SPOOL_DIR/mail" ]; then
    mkdir -p "$TARGETMOUNT/$SLACK_SPOOL_DIR/mail"
    chmod 755 "$TARGETMOUNT/$SLACK_SPOOL_DIR"
    chown root.mail "$TARGETMOUNT/$SLACK_SPOOL_DIR/mail"
    chmod 775 "$TARGETMOUNT/$SLACK_SPOOL_DIR/mail"
  fi
}

set_timezone() {
  if [ -n "$TIMEZONE" -a -d "$TARGETMOUNT/usr/lib/zoneinfo" ]; then
    echo "### setting timezone to $TIMEZONE..."
    ( cd $TARGETMOUNT/usr/lib/zoneinfo ; ln -sf $TIMEZONE localtime )
    move_setup_hook "$SLACK_TIMECONFIG"
  fi
}

install_lilo() {
  if [ -x "$TARGETMOUNT/sbin/lilo" ]; then
    echo "### installing lilo..."
    BOOTDEV=`echo "$ROOTDEV" | sed 's/[0-9][0-9]*$//'`
    if [ "$BOOTDEV" = "$ROOTDEV" ]; then
      BOOTDEV=/dev/hda
    fi
    if [ -r "$TARGETMOUNT/etc/lilo.conf" ]; then
      mv "$TARGETMOUNT/etc/lilo.conf" "$TARGETMOUNT/etc/lilo.conf.bak"
    fi
    cat > "$TARGETMOUNT/etc/lilo.conf" << EOF
# LILO configuration file
# generated by autoinst
#
# Start LILO global section
boot = $BOOTDEV
#compact        # faster, but won't work on all systems.
# delay = 5
vga = normal    # force sane state
ramdisk = 0     # paranoia setting
# End LILO global section
# Linux bootable partition config begins
image = /vmlinuz
  root = $ROOTDEV
  label = Linux
# Linux bootable partition config ends
EOF
    chmod 644 "$TARGETMOUNT/etc/lilo.conf"
    ( cd "$TARGETMOUNT/sbin" ; ./lilo -r "$TARGETMOUNT" -m /boot/map -C /etc/lilo.conf )
    move_setup_hook "$SLACK_LILOCONFIG"
  fi
}

install_autoconf_hook() {
  if [ ! -d "$TARGETMOUNT/etc/rc.d" ]; then
    mkdir -p "$TARGETMOUNT/etc/rc.d"
  fi
  if [ ! -f "$TARGETMOUNT/etc/rc.d/rc.local" ]; then
    touch "$TARGETMOUNT/etc/rc.d/rc.local"
    chmod 644 "$TARGETMOUNT/etc/rc.d/rc.local"
  fi
  cp "$SOURCEMOUNT/autoinst.d/autoconf.sh" "$TARGETMOUNT/autoconf.sh"
  chmod +x "$TARGETMOUNT/autoconf.sh"
  echo "if [ -x /autoconf.sh ]; then" >> "$TARGETMOUNT/etc/rc.d/rc.local"
  echo "  /autoconf.sh" >> "$TARGETMOUNT/etc/rc.d/rc.local"
  echo "fi" >> "$TARGETMOUNT/etc/rc.d/rc.local"
}

install_pkgtool_sets
write_rootdev
copy_setup_binaries
install_fstab
fix_permissions
set_timezone
install_lilo
install_autoconf_hook
