# installer for pkgtool-based Slackware versions

normalize_sets() {
  SETS=`echo $SETS | sed 's/[ ;,]/#/g'`
}

move_setup_hook() {
  if [ -f "$ROOTMOUNT/$1" ]; then
    if [ ! -d "$ROOTMOUNT/$SLACK_ADM_DIR/setup/install" ]; then
      mkdir -p "$ROOTMOUNT/$SLACK_ADM_DIR/setup/install"
    fi
    mv "$ROOTMOUNT/$1" "$ROOTMOUNT/$SLACK_ADM_DIR/setup/install"
  fi
}

install_pkgtool_sets() {
  echo "### installing packages..."
  normalize_sets
  if [ ! -d "$INSTMOUNT/tmp" ]; then
    mkdir -p "$INSTMOUNT/tmp"
  fi
  rm -f "$INSTMOUNT/tmp/tagfile"
  echo ".new" > /tmp/custom
  "$SLACK_PKGTOOL_SOURCE" -source_mounted -source_dir $INSTMOUNT -target_dir $ROOTMOUNT -sets "#$SETS#"
  rm -f /tmp/custom
}

write_rootdev() {
  if [ ! -d "$ROOTMOUNT/etc/rc.d" ]; then
    mkdir -p "$ROOTMOUNT/etc/rc.d"
  fi
  if [ ! -r "$ROOTMOUNT/etc/rc.d/ROOTDEV" ]; then
    echo "$ROOTDEV" > "$ROOTMOUNT/etc/rc.d/ROOTDEV"
    chmod 644 "$ROOTMOUNT/etc/rc.d/ROOTDEV"
  fi
}

install_fstab() {
  if [ ! -r "$ROOTMOUNT/etc/fstab" -a -r "$ROOTMOUNT/fstab.tmp" ]; then
    mv "$ROOTMOUNT/fstab.tmp" "$ROOTMOUNT/etc/fstab"
    chmod 644 "$ROOTMOUNT/etc/fstab"
  fi
  if [ -r "$ROOTMOUNT/etc/fstab" ]; then
    fgrep "/proc" "$ROOTMOUNT/etc/fstab" >/dev/null 2>&1
    if [ ! $? = 0 ]; then
      echo "none        /proc        proc        defaults" >> "$ROOTMOUNT/etc/fstab"
      echo " " >> "$ROOTMOUNT/etc/fstab"
    fi
  fi
}

fix_permissions() {
  echo "### fixing permissions..."
  ( cd $ROOTMOUNT ; chmod 755 ./ )
  if [ -d "$ROOTMOUNT/var" ]; then
    ( cd $ROOTMOUNT ; chmod 755 ./var )
  fi
  if [ -d "$ROOTMOUNT/usr/src/linux" ]; then
    chmod 755 "$ROOTMOUNT/usr/src/linux"
  fi
  if [ ! -d "$ROOTMOUNT/proc" ]; then
    mkdir "$ROOTMOUNT/proc"
    chown root.root "$ROOTMOUNT/proc"
  fi
  if [ ! -L "$ROOTMOUNT/lib/cpp" ]; then
    ( cd $ROOTMOUNT/lib ; ln -sf /usr/lib/gcc-lib/i486-linux/*.*.*/cpp cpp )
  fi
  if [ ! -d "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucp" ]; then
    mkdir -p "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucp"
  fi
  chown uucp.uucp "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucp"
  chmod 1777 "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucp"
  if [ ! -d "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucppublic" ]; then
    mkdir -p "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucppublic"
  fi
  chown uucp.uucp "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucppublic"
  chmod 1777 "$ROOTMOUNT/$SLACK_SPOOL_DIR/uucppublic"
  chmod 1777 "$ROOTMOUNT/tmp"
  if [ ! -d "$ROOTMOUNT/$SLACK_SPOOL_DIR/mail" ]; then
    mkdir -p "$ROOTMOUNT/$SLACK_SPOOL_DIR/mail"
    chmod 755 "$ROOTMOUNT/$SLACK_SPOOL_DIR"
    chown root.mail "$ROOTMOUNT/$SLACK_SPOOL_DIR/mail"
    chmod 775 "$ROOTMOUNT/$SLACK_SPOOL_DIR/mail"
  fi
}

set_timezone() {
  if [ -n "$TIMEZONE" -a -d "$ROOTMOUNT/usr/lib/zoneinfo" ]; then
    echo "### setting timezone to $TIMEZONE..."
    ( cd $ROOTMOUNT/usr/lib/zoneinfo ; ln -sf $TIMEZONE localtime )
    move_setup_hook "$SLACK_TIMECONFIG"
  fi
}

install_lilo() {
  if [ -x "$ROOTMOUNT/sbin/lilo" ]; then
    echo "### installing lilo..."
    BOOTDEV=`echo "$ROOTDEV" | sed 's/[0-9][0-9]*$//'`
    if [ "$BOOTDEV" = "$ROOTDEV" ]; then
      BOOTDEV=/dev/hda
    fi
    if [ -r "$ROOTMOUNT/etc/lilo.conf" ]; then
      mv "$ROOTMOUNT/etc/lilo.conf" "$ROOTMOUNT/etc/lilo.conf.bak"
    fi
    cat > "$ROOTMOUNT/etc/lilo.conf" << EOF
# LILO configuration file
# generated by autoinst
#
# Start LILO global section
boot = $BOOTDEV
#compact        # faster, but won't work on all systems.
# delay = 5
vga = normal    # force sane state
ramdisk = 0     # paranoia setting
# End LILO global section
# Linux bootable partition config begins
image = /vmlinuz
  root = $ROOTDEV
  label = Linux
  read-only
# Linux bootable partition config ends
EOF
    chmod 644 "$ROOTMOUNT/etc/lilo.conf"
    if [ -x $ROOTMOUNT/usr/lib/setup/bin/lilo ]; then
      # On slackware ELF distributions, /sbin/lilo is not usable from the installation
      # environment, so we have to use a.out the version in /usr/lib/setup/bin instead
      $ROOTMOUNT/usr/lib/setup/bin/lilo -r "$ROOTMOUNT" -m /boot/map -C /etc/lilo.conf
    elif [ -x $ROOTMOUNT/sbin/lilo ]; then
      $ROOTMOUNT/sbin/lilo -r "$ROOTMOUNT" -m /boot/map -C /etc/lilo.conf
    else
      echo "Warning: could not find lilo binary. System may be unbootable!"
    fi
    move_setup_hook "$SLACK_LILOCONFIG"
  fi
}

install_autoconf_hook() {
  if [ ! -d "$ROOTMOUNT/etc/rc.d" ]; then
    mkdir -p "$ROOTMOUNT/etc/rc.d"
  fi
  if [ ! -f "$ROOTMOUNT/etc/rc.d/rc.local" ]; then
    touch "$ROOTMOUNT/etc/rc.d/rc.local"
    chmod 644 "$ROOTMOUNT/etc/rc.d/rc.local"
  fi
  cp "$INSTMOUNT/autoinst.d/autoconf.sh" "$ROOTMOUNT/autoconf.sh"
  chmod +x "$ROOTMOUNT/autoconf.sh"
  echo "if [ -x /autoconf.sh ]; then" >> "$ROOTMOUNT/etc/rc.d/rc.local"
  echo "  /autoconf.sh" >> "$ROOTMOUNT/etc/rc.d/rc.local"
  echo "fi" >> "$ROOTMOUNT/etc/rc.d/rc.local"
}

install_pkgtool_sets
write_rootdev
install_fstab
fix_permissions
set_timezone
install_lilo
install_autoconf_hook
