#!/bin/sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
T_PX="`cat $TMP/SeTT_PX`"
ROOT_DEVICE="`cat $TMP/SeTrootdev`"
if [ ! -d $T_PX/bin -a ! -d $T_PX/etc ]; then # if there no Linux here, exit
 exit
fi
# Check for disk full error:
. /usr/lib/setup/SeTfull
# These next lines are intended to clean up any permissions
# problems that could be caused by a bad package.  We don't
# intend to make any bad packages here, but it never hurts
# to be safe. :^)
( cd $T_PX ; chmod 755 ./ )
( cd $T_PX ; chmod 755 ./var )
if [ -d $T_PX/usr/src/linux ]; then
 chmod 755 $T_PX/usr/src/linux
fi
if [ ! -d $T_PX/proc ]; then
 mkdir $T_PX/proc
 chown root.root $T_PX/proc
fi
chmod 1777 $T_PX/tmp
if [ ! -d $T_PX/var/spool/mail ]; then
 mkdir -p $T_PX/var/spool/mail
 chmod 755 $T_PX/var/spool
 chown root.mail $T_PX/var/spool/mail
 chmod 1777 $T_PX/var/spool/mail
fi 

# Load keyboard map (if any) when booting
if [ -r $TMP/SeTkeymap ]; then
 MAPNAME="`cat $TMP/SeTkeymap`"
 echo "#!/bin/sh" > $T_PX/etc/rc.d/rc.keymap
 echo "# Load the keyboard map.  More maps are in /usr/share/kbd/keymaps." \
 >> $T_PX/etc/rc.d/rc.keymap
 echo "if [ -x /usr/bin/loadkeys ]; then" >> $T_PX/etc/rc.d/rc.keymap
 echo " /usr/bin/loadkeys $MAPNAME" >> $T_PX/etc/rc.d/rc.keymap
 echo "fi" >> $T_PX/etc/rc.d/rc.keymap
 chmod 755 $T_PX/etc/rc.d/rc.keymap
fi

# Install the bootdisk's Linux kernel:
. /usr/lib/setup/SeTkernel

# Only ask if we want to skip configuring if we suspect the user should
# skip the step:
if [ -r $T_PX/etc/fstab ]; then
 dialog --title "CONFIGURE THE SYSTEM" --yesno "Now we can configure your \
Linux system. If this is a new installation, you MUST configure it now or it \
will not boot correctly. However, if you are just adding software to an \
existing system, you can back out to the main menu and skip this step. \
However (important exception) if you've installed a new kernel image, it's \
important to reconfigure your system so that you can install LILO (the Linux \
loader) or create a bootdisk using the new kernel. You want to CONFIGURE \
your system, right?" 0 0
 if [ ! $? = 0 ]; then
  exit
 fi
fi
while [ 0 ]; do # the bootdisk menu loop
 dialog --title "MAKE BOOTDISK" --ok-label Create --cancel-label Skip --menu \
"It is highly recommended that you make \
a bootdisk (or two) for your system at this time.  Please insert a floppy disk \
(formatted or unformatted) and press ENTER to create a bootdisk.  \n\
\n\
The existing contents of the floppy disk will be erased." 13 70 2 \
 "Create" "Make a Linux bootdisk in /dev/fd0" \
 "Skip" "Skip making a bootdisk" \
 2> $TMP/return
 REPLY=`cat $TMP/return`
 rm -f $TMP/return
 if [ "$REPLY" = "Create" ]; then
   dialog --title "Formatting /dev/fd0u1680" --infobox "Formatting /dev/fd0, \
1.68 megabytes." 3 42
   if [ -x /sbin/fdformat ]; then
     /sbin/fdformat -n /dev/fd0u1680 1> /dev/null 2> /dev/null
   else
     chroot $T_PX fdformat -n /dev/fd0u1680 1> /dev/null 2> /dev/null
   fi
   if [ ! $? = 0 ]; then
     dialog --title "ERROR: FLOPPY FORMAT FAILED" --msgbox "The attempt to format the floppy \
disk in /dev/fd0 has failed, probably due to bad media.  Please try again with a \
different disk.  If that doesn't work, perhaps the drive needs cleaning." 0 0
    continue
   fi
  rm -f $TMP/return
  dialog --title "CREATING BOOT FLOPPY" --infobox "Creating SYSLINUX bootdisk for \
$ROOT_DEVICE in /dev/fd0." 3 64 
   if [ -x /sbin/mkdosfs ]; then
     /sbin/mkdosfs -F 12 /dev/fd0u1680 1680 1> /dev/null 2> /dev/null
   else
     chroot $T_PX /sbin/mkdosfs -F 12 /dev/fd0u1680 1680 1> /dev/null 2> /dev/null
   fi
   if [ ! -d $TMP/bootdisk ]; then
    mkdir $TMP/bootdisk
   fi
   mount -t vfat /dev/fd0 $TMP/bootdisk 1> /dev/null 2> /dev/null
   if [ -r $T_PX/vmlinuz ]; then
     cp $T_PX/vmlinuz $TMP/bootdisk/vmlinuz
   elif [ -r $T_PX/boot/vmlinuz ]; then
     cp $T_PX/boot/vmlinuz $TMP/bootdisk/vmlinuz
   fi
   ## This avoids a syslinux-1.72 bug, and doesn't seem to hurt anything:
   #dd if=/dev/zero bs=1k count=1 >> $TMP/bootdisk/vmlinuz 2> /dev/null
   cat << EOF > $TMP/bootdisk/message.txt

Welcome to the 09Slackware07 Linux custom bootdisk!

By default, this disk boots a root Linux partition on $ROOT_DEVICE when you
hit ENTER.  If you'd like to boot some other partition, use a command like
this on the prompt below:

    mount root=/dev/sda1 ro

Where "/dev/sda1" is the partition you want to boot, and "ro" specifies that
the partition should be initially mounted as read-only.  If you wish to mount
the partition read-write, use "rw" instead.  To set the video console mode,
use the vga= parameter (press F1 to see a table).  You may also add any other
kernel parameters you might need depending on your hardware, and which
drivers are included in your kernel.

EOF
   cat << EOF > $TMP/bootdisk/syslinux.cfg
default vmlinuz ramdisk_size=7000 root=$ROOT_DEVICE vga=normal ro
prompt 1
timeout 6000
display message.txt
F1 f1.txt
F2 message.txt
#F3 f3.txt
#F4 f4.txt
#F5 f5.txt
#F6 f6.txt
#F7 f7.txt
label mount
  kernel vmlinuz
  append ramdisk_size=7000 root=$ROOT_DEVICE vga=normal ro
label ramdisk
  kernel vmlinuz
  append vmlinuz ramdisk_size=7000 root=/dev/fd0u1440 vga=normal rw
EOF
  cat << EOF > $TMP/bootdisk/f1.txt
 STANDARD MODES:
 To make the kernel prompt for standard video modes use: vga=ask

 FRAMEBUFFER MODES:
 To get the kernel to start in VESA framebuffer mode, you need to pass it
 a vga= init string on the "boot:" prompt.  Here's a table:

   Colors   640x480 800x600 1024x768 1280x1024 1600x1200
  --------+---------------------------------------------
  256     |   769     771      773      775       796
  32,768  |   784     787      790      793       797
  65,536  |   785     788      791      794       798
  16.8M   |   786     789      792      795       799

  ...such as this for 1024x768x64k:
   vga=791

  F2 returns to the previous page.

EOF
  umount /dev/fd0
  syslinux -s /dev/fd0
  rm -r $TMP/bootdisk
  dialog --title "BOOTDISK CREATED" --ok-label Continue --cancel-label Create --menu \
"The boot floppy has been successfully created in /dev/fd0.  If you would like to \
create an additional bootdisk, please select 'Create' and we'll go back and make another \
one, otherwise select 'Continue' to continue configuring your system." 12 70 2 \
 "Continue" "Continue the configuration (done making bootdisks)" \
 "Create" "Make a spare Linux bootdisk in /dev/fd0" \
 2> $TMP/return
  REPLY=`cat $TMP/return`
  rm -f $TMP/return
  if [ "$REPLY" = "Create" ]; then
   continue
  else
   break
  fi
 else # ! Create
  break
 fi
done
   
dialog --title "MODEM CONFIGURATION" --menu "This part of the configuration \
process will create a /dev/modem link pointing to the callout device (ttyS0, \
ttyS1, ttyS2, ttyS3) representing your default modem.  You \
can change this link \
later if you move your modem to a different port.  If your modem is a PCI card, \
it will probably use /dev/ttyS4 or higher. \
Please select the callout \
device which you would like to use for your modem:" 22 68 9 \
"no modem" "I don't have a modem!" \
"/dev/ttyS0" "(COM1: under DOS)" \
"/dev/ttyS1" "(COM2: under DOS)" \
"/dev/ttyS2" "(COM3: under DOS)" \
"/dev/ttyS3" "(COM4: under DOS)" \
"/dev/ttyS4" "PCI modem" \
"/dev/ttyS5" "PCI modem" \
"/dev/ttyS6" "PCI modem" \
"/dev/ttyS7" "PCI modem" \
"/dev/ttyS8" "PCI modem" \
"/dev/ttyS9" "PCI modem" \
"/dev/ttyS10" "PCI modem" \
"/dev/ttyS11" "PCI modem" \
"/dev/ttyS12" "PCI modem" \
"/dev/ttyS13" "PCI modem" \
"/dev/ttyS14" "PCI modem" \
"/dev/ttyS15" "PCI modem" \
2> $TMP/callout
if [ $? = 0 ]; then
 MODEM_DEVICE="`cat $TMP/callout`"
 if [ ! "$MODEM_DEVICE" = "no modem" ]; then
  MODEM_DEVICE=`basename $MODEM_DEVICE`
  (cd $T_PX/dev; ln -sf $MODEM_DEVICE modem)
 fi
fi
rm -f $TMP/callout

# Post installation and setup scripts added by packages.
if [ -d $T_PX/var/log/setup ]; then
 for INSTALL_SCRIPTS in $T_PX/var/log/setup/setup.*
 do
  SCRIPT=`basename $INSTALL_SCRIPTS`
  # Here, we call each script in /var/log/setup. Two arguments are provided:
  # 1 -- the target prefix (normally /, but /mnt from the bootdisk)
  # 2 -- the name of the root device.
  ( cd $T_PX ; sh var/log/setup/$SCRIPT $T_PX $ROOT_DEVICE )
  if echo $SCRIPT | fgrep onlyonce 1> /dev/null 2> /dev/null; then # only run after first install
   if [ ! -d $T_PX/var/log/setup/install ]; then
    mkdir $T_PX/var/log/setup/install
   fi
   mv $INSTALL_SCRIPTS $T_PX/var/log/setup/install
  fi
 done
fi

# Set root password:
/usr/lib/setup/SeTpasswd

