#!/bin/sh
T_PX="`cat /tmp/SeTT_PX`"
ROOT_DEVICE="`cat /tmp/SeTrootdev`"
if [ ! -d $T_PX/bin -a ! -d $T_PX/etc ]; then # if there no Linux here, exit
 exit
fi
dialog --title "CONFIGURE YOUR SYSTEM?" --yesno "Now it's time to configure \
your Linux system. If this is a new system, you must configure it now or it \
will not boot correctly. Otherwise, you can back out to the main menu if \
you're sure you want to skip this step. If you've installed a new kernel \
image, it's important to reconfigure your system so that you can install LILO \
(the Linux loader) or create a bootdisk using the new kernel. Do you want to \
move on to \
the CONFIGURE option?" 14 60 
if [ $? = 1 -o $? = 255 ]; then
 exit
fi
while [ 0 ]; do # the bootdisk menu loop
 dialog --title "MAKE BOOTDISK" --menu "It is highly recommended that you make\
 a bootdisk (or two) for your system at this time.  There are two types of \
bootdisks that you can make:  a simple bootdisk (which is just a kernel image \
written directly to disk) or a LILO bootdisk (which is more flexible, but \
takes a little longer to load).  Which option would you like?" 15 74 4 \
"format" "format floppy disk in /dev/fd0" \
"simple" "make simple vmlinuz > /dev/fd0 bootdisk" \
"lilo" "make lilo bootdisk" \
"continue" "leave bootdisk menu and continue with the configuration" 2> /tmp/return
 if [ ! $? = 0 ]; then
  break;
 fi
 REPLY=`cat /tmp/return`
 rm -f /tmp/return
 if [ "$REPLY" = "format" ]; then
  dialog --title "SPECIFY FLOPPY SIZE" --menu "What size is your /dev/fd0 (a:)\
 drive?" 9 60 2 \
"1.44" "1.44 megabytes" \
"1.2" "1.2 megabytes" 2> /tmp/return
  if [ "`cat /tmp/return`" = "1.44" ]; then
   dialog --title "Formatting /dev/fd0H1440" --infobox "Formatting /dev/fd0, \
1.44 megabytes." 3 50 
   fdformat -n /dev/fd0H1440 1> /dev/null 2> /dev/null
  elif [ "`cat /tmp/return`" = "1.2" ]; then
   dialog --title "Formatting /dev/fd0h1200" --infobox "Formatting /dev/fd0, \
1.2 megabytes." 3 50
   fdformat -n /dev/fd0h1200 1> /dev/null 2> /dev/null
  fi
  rm -f /tmp/return
 elif [ "$REPLY" = "simple" ]; then # make simple bootdisk
  dialog --title "BOOT DISK CREATION" --yesno \
"\n\
Now put a formatted floppy in your boot drive. \n\
This will be made into your Linux boot disk. Use this to\n\
boot Linux until LILO has been configured to boot from\n\
the hard drive.\n\n\
Any data on the target disk will be destroyed.\n\n\
YES creates the disk, NO aborts.\n" 14 62
  if [ $? = 0 ]; then
   dialog --title "CREATING DISK" --infobox "Creating boot disk from 'vmlinuz'..." 5 50
   KERNEL="/vmlinuz"
   dd if=$T_PX$KERNEL of=/dev/fd0 2> /dev/null
   rdev /dev/fd0 $ROOT_DEVICE
   rdev -v /dev/fd0 -1
   rdev -R /dev/fd0 1
   sync
  fi
 elif [ "$REPLY" = "lilo" ]; then # make lilo bootdisk
  dialog --title "CREATING LILO BOOTDISK IN /dev/fd0" --yesno "Now put a \
formatted floppy in your boot drive.  This will be made into a LILO \
bootdisk that you can use to start your Linux system.  Any data on the \
target disk will be destroyed.  YES creates the disk, NO aborts." 8 62
  if [ $? = 0 ]; then # make the disk
   dialog --title "SPECIFY FLOPPY SIZE" --menu "What size is your /dev/fd0 (a:)\
 drive?" 9 60 2 \
"1.44" "1.44 megabytes" \
"1.2" "1.2 megabytes" 2> /tmp/return
   if [ "`cat /tmp/return`" = "1.44" ]; then
    DEV=/dev/fd0H1440
   else
    DEV=/dev/fd0h1200
   fi
   dialog --infobox "Creating LILO bootdisk for $ROOT_DEVICE..." 3 60
   mke2fs $DEV 1> /dev/null 2> /dev/null
   if [ ! -d /tmp/lilo ]; then
    mkdir /tmp/lilo
   fi
   mount -t ext2 /dev/fd0 /tmp/lilo 1> /dev/null 2> /dev/null
   cp $T_PX/vmlinuz /tmp/lilo/vmlinuz
   cp -a /dev /tmp/lilo
   mkdir /tmp/lilo/etc
   cat << EOF > /tmp/lilo/etc/lilo.conf
boot = /dev/fd0
message=/boot/message
prompt
image = /vmlinuz
        label = mount
        ramdisk = 0
        root = $ROOT_DEVICE
        vga = normal
        read-only
EOF
   cp -a /boot /tmp/lilo
   cat << EOF > /tmp/lilo/boot/message

Welcome to the Slackware Linux custom LILO bootdisk!  

By default, this disk boots a root Linux partition on $ROOT_DEVICE when
you hit ENTER.  If you'd like to boot some other partition, use a command
like this on the LILO prompt below:

    mount root=/dev/sda1 ro

Where "/dev/sda1" is the partition you want to boot, and "ro" specifies that
the partition should be initially mounted as read-only.  If you wish to mount
the partition read-write, use "rw" instead.  You may also add any other kernel
parameters you might need depending on your hardware, and which drivers are
included in your kernel.

EOF
   lilo -r /tmp/lilo 1> /dev/null 2> /dev/null
   umount /tmp/lilo
   rm -rf /tmp/lilo
  fi
 elif [ "$REPLY" = "continue" ]; then
  break;
 fi
done
dialog --title "MODEM CONFIGURATION" --yesno \
"\n\
This part of the configuration process will create a link in /dev\n\
from your callout device (cua0, cua1, cua2, cua3) to /dev/modem.\n\
You can change this link later if you put your modem on a different\n\
port.\n\n\
Would you like to set up your modem?\n" 12 73
if [ $? = 0 ]; then
 dialog --title "SELECT CALLOUT DEVICE" \
--menu "Please select the callout device which you would like to use \
for your modem:" 12 60 4 \
"cua0" "com1: under DOS" \
"cua1" "com2: under DOS" \
"cua2" "com3: under DOS" \
"cua3" "com4: under DOS" 2> /tmp/callout
 if [ $? = 1 ]; then
  rm -f /tmp/callout
 else
  MODEM_DEVICE="`cat /tmp/callout`"
  rm -f /tmp/callout
  (cd $T_PX/dev; ln -sf $MODEM_DEVICE modem)
 fi
fi


dialog --title "MOUSE CONFIGURATION" \
--yesno "\n\
This part of the configuration process will create a link in /dev\n\
from your mouse device to /dev/mouse. You can change this link\n\
later if the setting chosen does not work, or if you switch to a\n\
different type of mouse.\n\n\
Would you like to set up your mouse?" 12 70
if [ $? = 0 ]; then
 dialog --title "SELECT MOUSE TYPE" --menu "These mouse types are supported:" 14 60 7 \
"1" "Microsoft compatible serial mouse" \
"2" "C&T 82C710 or PS/2 style mouse (Auxiliary port)" \
"3" "Logitech Bus Mouse" \
"4" "ATI XL Bus Mouse" \
"5" "Microsoft Bus Mouse" \
"6" "Mouse Systems serial mouse" \
"7" "Logitech (MouseMan) serial mouse" 2> /tmp/mtype
 if [ $? = 1 ]; then
  rm -f /tmp/mtype
 fi
 if [ -f /tmp/mtype ]; then
  MOUSE_TYPE="`cat /tmp/mtype`"
 else
  unset MOUSE_TYPE
 fi
 rm -f /tmp/mtype
 if [ "$MOUSE_TYPE" = "1" -o "$MOUSE_TYPE" = "6" -o "$MOUSE_TYPE" = "7" ]; then
  dialog --title "SELECT SERIAL PORT" --menu "Your mouse requires a serial port. Which one would you \
like to use?" 12 60 4 \
"ttyS0" "com1: under DOS" \
"ttyS1" "com2: under DOS" \
"ttyS2" "com3: under DOS" \
"ttyS3" "com4: under DOS" 2> /tmp/mport
  if [ $? = 1 ]; then
   rm -f /tmp/mport
  fi
  if [ -f /tmp/mport ]; then
   MOUSE_DEVICE="`cat /tmp/mport`"
  else
   unset MOUSE_DEVICE
  fi
  rm -f /tmp/mport
  if [ "$MOUSE_TYPE" = "1" ]; then
   MTYPE="ms"
  elif [ "$MOUSE_TYPE" = "7" ]; then
   MTYPE="mman"
  else
   MTYPE="msc"
  fi
  (cd $T_PX/dev; ln -sf $MOUSE_DEVICE mouse)
 elif [ "$MOUSE_TYPE" = "2" ]; then
  (cd $T_PX/dev; ln -sf psaux mouse)
  MTYPE="ps2"
 elif [ "$MOUSE_TYPE" = "3" ]; then
  (cd $T_PX/dev; ln -sf logibm mouse)
  MTYPE="logi"
 elif [ "$MOUSE_TYPE" = "4" ]; then
  (cd $T_PX/dev; ln -sf atibm mouse)
  MTYPE="bm"
 elif [ "$MOUSE_TYPE" = "5" ]; then
  (cd $T_PX/dev; ln -sf inportbm mouse)
  MTYPE="bm"
 fi
fi
export MTYPE

( cd $T_PX ; chmod 755 ./ )
( cd $T_PX ; chmod 755 ./var )
if [ -d $T_PX/usr/src/linux ]; then
 chmod 755 $T_PX/usr/src/linux
fi
if [ ! -d $T_PX/proc ]; then
 mkdir $T_PX/proc
 chown root.root $T_PX/proc
fi
if [ ! -d $T_PX/var/spool/uucp ]; then
 mkdir -p $T_PX/var/spool/uucp
fi
chown uucp.uucp $T_PX/var/spool/uucp
chmod 1777 $T_PX/var/spool/uucp
if [ ! -d $T_PX/var/spool/uucppublic ]; then
 mkdir -p $T_PX/var/spool/uucppublic
fi
chown uucp.uucp $T_PX/var/spool/uucppublic
chmod 1777 $T_PX/var/spool/uucppublic
chmod 1777 $T_PX/tmp
if [ ! -d $T_PX/var/spool/mail ]; then
 mkdir -p $T_PX/var/spool/mail
 chmod 755 $T_PX/var/spool
 chown root.mail $T_PX/var/spool/mail
 chmod 775 $T_PX/var/spool/mail
fi 

# Post installation and setup scripts added by packages.
if [ -d $T_PX/var/adm/setup ]; then
 for INSTALL_SCRIPTS in $T_PX/var/adm/setup/setup.*
 do
  SCRIPT=`basename $INSTALL_SCRIPTS`
  # Here, we call each script in /var/adm/setup. Two arguments are provided:
  # 1 -- the target prefix (normally /, but /mnt from the bootdisk)
  # 2 -- the name of the root device.
  ( cd $T_PX ; sh var/adm/setup/$SCRIPT $T_PX $ROOT_DEVICE )
  if echo $SCRIPT | fgrep onlyonce 1> /dev/null 2> /dev/null; then # only run after first install
   if [ ! -d $T_PX/var/adm/setup/install ]; then
    mkdir $T_PX/var/adm/setup/install
   fi
   mv $INSTALL_SCRIPTS $T_PX/var/adm/setup/install
  fi
 done
fi

# Load keyboard map (if any) when booting
if [ -r /tmp/SeTkeymap ]; then
 MAPNAME="`cat /tmp/SeTkeymap`"
 if fgrep "sh /etc/rc.d/rc.keymap" $T_PX/etc/rc.d/rc.local 1> /dev/null 2> /dev/null ; then
  echo >> /dev/null # ?
 else
  echo "# Load custom keyboard map" >> $T_PX/etc/rc.d/rc.local
  echo "sh /etc/rc.d/rc.keymap" >> $T_PX/etc/rc.d/rc.local
 fi
 mkdir -p $T_PX/usr/lib/kbd/keytables
 if [ ! -r $T_PX/usr/lib/kbd/keytables/$MAPNAME ]; then
  cp /tmp/$MAPNAME $T_PX/usr/lib/kbd/keytables
  chmod 755 $T_PX/usr/lib/kbd/keytables
 fi
 echo "#!/bin/sh" > $T_PX/etc/rc.d/rc.keymap
 echo "echo 'Loading keyboard map \"$MAPNAME\"...'" >> $T_PX/etc/rc.d/rc.keymap
 echo "/usr/bin/loadkeys /usr/lib/kbd/keytables/$MAPNAME" >> $T_PX/etc/rc.d/rc.keymap
 chmod 755 $T_PX/etc/rc.d/rc.keymap
fi
