#!/bin/sh

dialog --title "SOURCE MEDIA SELECTION" --menu \
"\nWhere do you plan to install Slackware Linux from?\n" 14 65 5 \
"1" "Install from a hard drive partition" \
"2" "Install from floppy disks" \
"3" "Install via NFS" \
"4" "Install from a pre-mounted directory" \
"5" "Install from CD-ROM"  2> /tmp/media
if [ $? = 1 -o $? = 255 ]; then
 rm /tmp/media
 exit
fi

SOURCE_MEDIA="`cat /tmp/media`"
rm -f /tmp/media
if [ "$SOURCE_MEDIA" = "1" ]; then
 INShd
elif [ "$SOURCE_MEDIA" = "2" ]; then
 INSfd
elif [ "$SOURCE_MEDIA" = "3" ]; then
 INSNFS
elif [ "$SOURCE_MEDIA" = "4" ]; then
 INSdir 
elif [ "$SOURCE_MEDIA" = "5" ]; then
 INSCD
fi
