#!/bin/sh
dialog --title "CHANGE INSTALL MODE" --menu "There are two basic modes \
of installation, QUICK and VERBOSE. In VERBOSE mode, you will be given \
a description of each optional package as it is about to be installed, \
and will be asked if you wish to install it. In QUICK mode, you are only \
asked once at the beginning of each disk set. QUICK mode does not give \
as complete a description of each package, so beginners should probably \
stick to VERBOSE mode at first. If you use QUICK mode, it won't matter \
what kind of tagfiles you specify later - you will be prompted to choose \
at the start of each disk series. Which mode would you like to use?" \
18 70 2 \
"VERBOSE" "Use verbose installation mode" \
"QUICK" "Use quick and terse install mode" 2> /tmp/SeTreturn
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTreturn
 exit
fi
if [ "`cat /tmp/SeTreturn`" = "VERBOSE" ]; then
 rm -f /tmp/SeTQUICK
else
 touch /tmp/SeTQUICK
fi
rm -f /tmp/SeTreturn
