[qemu]
profile = "linux-0.99"

[qemu.serial]
auxiliary = "msmouse"

[download]
cdrom = "infomagic/ldr/1994_06"

[extract]
source = "disc1.iso"
package_source = "distributions/debian/dist/packages"
boot_link = "bootdisk"
extra_images = ["distributions/debian/dist/base/bootdisk.gz", "distributions/debian/dist/base/basedsk1.gz", "distributions/debian/dist/base/basedsk2.gz"]
decompress = ["*.gz"]

[install]
driver = "debian-091"

[install.network]
hostname = "debra"
domain = "retro.net"
ip = "10.0.2.15"
network = "10.0.2.0"
broadcast = "10.0.2.255"
gateway = "10.0.2.2"
netmask = "255.255.255.0"
nameserver = "10.0.2.3"

[install.locale]
timezone = "US/Central"

[postinst]
custom_script = "postinst.sh"
stages = ["custom", "tty", "x11"]

[postinst.x11]
mouse_device = "/dev/ttyS2"
