# configure X11 for Cirrus card emulated by QEMU
echo "### Configuring X11..."

# XFree86 3.1 uses XF86Config with R6 paths. Older releases use Xconfig.
if [ -x /usr/X11R6/bin/XF86_SVGA ] || [ -x /usr/X11R6/bin/XF86_VGA16 ] || [ -x /usr/X11R6/bin/XF86_Mono ]; then

# Link to the correct X server
for SERVER in /usr/X11R6/bin/XF86_SVGA /usr/X11R6/bin/XF86_VGA16 /usr/X11R6/bin/XF86_Mono; do
  if [ -f "$SERVER" ]; then
    echo "Found X11 server at $SERVER"
    if [ -d /var/X11R6/bin ]; then
      (cd /var/X11R6/bin; ln -sf "$SERVER" X)
    fi
    break
  fi
done

if [ -x "$SERVER" ]; then
for X11PATH in /usr/X11R6/lib/X11 /var/X11R6/lib /etc; do
  if [ -d "$X11PATH" ]; then
    break
  fi
done

XFREECFG="$X11PATH/XF86Config"
XFREECFG_ETC=/etc/XF86Config

if [ -c /dev/psaux ]; then
  X11MOUSEDEV=psaux
else
  X11MOUSEDEV=$MOUSEDEV
fi

echo "Creating XF86Config in $XFREECFG"

if [ -f "$XFREECFG" ]; then
    cp "$XFREECFG" "$XFREECFG.orig"
fi

cat > "$XFREECFG" <<EOF
# File generated by xf86config.

#
# Copyright (c) 1994 by The XFree86 Project, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE XFREE86 PROJECT BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
# Except as contained in this notice, the name of the XFree86 Project shall
# not be used in advertising or otherwise to promote the sale, use or other
# dealings in this Software without prior written authorization from the
# XFree86 Project.
#

# **********************************************************************
# Refer to the XF86Config(4/5) man page for details about the format of 
# this file.
# **********************************************************************

# **********************************************************************
# Files section.  This allows default font and rgb paths to be set
# **********************************************************************

Section "Files"

# The location of the RGB database.  Note, this is the name of the
# file minus the extension (like ".txt" or ".db").  There is normally
# no need to change the default.

    RgbPath	"/usr/X11R6/lib/X11/rgb"

# Multiple FontPath entries are allowed (which are concatenated together),
# as well as specifying multiple comma-separated entries in one FontPath
# command (or a combination of both methods)
# 
# If you don't have a floating point coprocessor and emacs, Mosaic or other
# programs take long to start up, try moving the Type1 and Speedo directory
# to the end of this list (or comment them out).
# 

    FontPath	"/usr/X11R6/lib/X11/fonts/misc/"
    FontPath	"/usr/X11R6/lib/X11/fonts/Type1/"
    FontPath	"/usr/X11R6/lib/X11/fonts/Speedo/"
    FontPath	"/usr/X11R6/lib/X11/fonts/75dpi/"
    FontPath	"/usr/X11R6/lib/X11/fonts/100dpi/"

EndSection

# **********************************************************************
# Server flags section.
# **********************************************************************

Section "ServerFlags"

# Uncomment this to cause a core dump at the spot where a signal is 
# received.  This may leave the console in an unusable state, but may
# provide a better stack trace in the core dump to aid in debugging

#    NoTrapSignals

# Uncomment this to disable the <Crtl><Alt><BS> server abort sequence
# This allows clients to receive this key event.

#    DontZap

# Uncomment this to disable the <Crtl><Alt><KP_+>/<KP_-> mode switching
# sequences.  This allows clients to receive these key events.

#    DontZoom

EndSection

# **********************************************************************
# Input devices
# **********************************************************************

# **********************************************************************
# Keyboard section
# **********************************************************************

Section "Keyboard"

    Protocol	"Standard"

# when using XQUEUE, comment out the above line, and uncomment the
# following line

#    Protocol	"Xqueue"

    AutoRepeat	500 5
# Let the server do the NumLock processing.  This should only be required
# when using pre-R6 clients
#    ServerNumLock

# Specifiy which keyboard LEDs can be user-controlled (eg, with xset(1))
#    Xleds      1 2 3

# To set the LeftAlt to Meta, RightAlt key to ModeShift, 
# RightCtl key to Compose, and ScrollLock key to ModeLock:

#    LeftAlt     Meta
#    RightAlt    ModeShift
#    RightCtl    Compose
#    ScrollLock  ModeLock

EndSection


# **********************************************************************
# Pointer section
# **********************************************************************

Section "Pointer"
    Protocol    "$MOUSETYPE"
    Device      "/dev/$X11MOUSEDEV"

# When using XQUEUE, comment out the above two lines, and uncomment
# the following line.

#    Protocol	"Xqueue"

# Baudrate and SampleRate are only for some Logitech mice

#    BaudRate	9600
#    SampleRate	150

# Emulate3Buttons is an option for 2-button Microsoft mice
# Emulate3Timeout is the timeout in milliseconds (default is 50ms)

    Emulate3Buttons
#    Emulate3Timeout    50

# ChordMiddle is an option for some 3-button Logitech mice

#    ChordMiddle

EndSection


# **********************************************************************
# Monitor section
# **********************************************************************

# Any number of monitor sections may be present

Section "Monitor"

    Identifier  "My Monitor"
    VendorName  "Unknown"
    ModelName   "Unknown"

# HorizSync is in kHz unless units are specified.
# HorizSync may be a comma separated list of discrete values, or a
# comma separated list of ranges of values.
# NOTE: THE VALUES HERE ARE EXAMPLES ONLY.  REFER TO YOUR MONITOR'S
# USER MANUAL FOR THE CORRECT NUMBERS.

    HorizSync   31.5 - 82.0

#    HorizSync	30-64         # multisync
#    HorizSync	31.5, 35.2    # multiple fixed sync frequencies
#    HorizSync	15-25, 30-50  # multiple ranges of sync frequencies

# VertRefresh is in Hz unless units are specified.
# VertRefresh may be a comma separated list of discrete values, or a
# comma separated list of ranges of values.
# NOTE: THE VALUES HERE ARE EXAMPLES ONLY.  REFER TO YOUR MONITOR'S
# USER MANUAL FOR THE CORRECT NUMBERS.

    VertRefresh 40-150

# Modes can be specified in two formats.  A compact one-line format, or
# a multi-line format.

# These two are equivalent

#    ModeLine "1024x768i" 45 1024 1048 1208 1264 768 776 784 817 Interlace

#    Mode "1024x768i"
#        DotClock	45
#        HTimings	1024 1048 1208 1264
#        VTimings	768 776 784 817
#        Flags		"Interlace"
#    EndMode

# This is a set of standard mode timings. Modes that are out of monitor spec
# are automatically deleted by the server (provided the HorizSync and
# VertRefresh lines are correct), so there's no immediate need to
# delete mode timings (unless particular mode timings don't work on your
# monitor). With these modes, the best standard mode that your monitor
# and video card can support for a given resolution is automatically
# used.

# 640x400 @ 70 Hz, 31.5 kHz hsync
Modeline "640x400"     25.175 640  664  760  800   400  409  411  450
# 640x480 @ 60 Hz, 31.5 kHz hsync
Modeline "640x480"     25.175 640  664  760  800   480  491  493  525
# 800x600 @ 56 Hz, 35.15 kHz hsync
ModeLine "800x600"     36     800  824  896 1024   600  601  603  625
# 1024x768 @ 87 Hz interlaced, 35.5 kHz hsync
Modeline "1024x768"    44.9  1024 1048 1208 1264   768  776  784  817 Interlace

# 640x480 @ 72 Hz, 36.5 kHz hsync
Modeline "640x480"     31.5   640  680  720  864   480  488  491  521
# 800x600 @ 60 Hz, 37.8 kHz hsync
Modeline "800x600"     40     800  840  968 1056   600  601  605  628 +hsync +vsync

# 800x600 @ 72 Hz, 48.0 kHz hsync
Modeline "800x600"     50     800  856  976 1040   600  637  643  666 +hsync +vsync
# 1024x768 @ 60 Hz, 48.4 kHz hsync
Modeline "1024x768"    65    1024 1032 1176 1344   768  771  777  806 -hsync -vsync

# 1024x768 @ 70 Hz, 56.5 kHz hsync
Modeline "1024x768"    75    1024 1048 1184 1328   768  771  777  806 -hsync -vsync
# 1280x1024 @ 87 Hz interlaced, 51 kHz hsync
Modeline "1280x1024"   80    1280 1296 1512 1568  1024 1025 1037 1165 Interlace

# 1024x768 @ 76 Hz, 62.5 kHz hsync
Modeline "1024x768"    85    1024 1032 1152 1360   768  784  787  823
# 1280x1024 @ 61 Hz, 64.2 kHz hsync
Modeline "1280x1024"  110    1280 1328 1512 1712  1024 1025 1028 1054

# 1280x1024 @ 74 Hz, 78.85 kHz hsync
Modeline "1280x1024"  135    1280 1312 1456 1712  1024 1027 1030 1064

# 1280x1024 @ 76 Hz, 81.13 kHz hsync
Modeline "1280x1024"  135    1280 1312 1416 1664  1024 1027 1030 1064

# Low-res Doublescan modes
# If your chipset does not support doublescan, you get a 'squashed'
# resolution like 320x400.

# 320x200 @ 70 Hz, 31.5 kHz hsync, 8:5 aspect ratio
# Modeline "320x200"     12.588 320  336  384  400   200  204  205  225 Doublescan
# 320x240 @ 60 Hz, 31.5 kHz hsync, 4:3 aspect ratio
# Modeline "320x240"     12.588 320  336  384  400   240  245  246  262 Doublescan
# 320x240 @ 72 Hz, 36.5 kHz hsync
# Modeline "320x240"     15.750 320  336  384  400   240  244  246  262 Doublescan
# 400x300 @ 56 Hz, 35.2 kHz hsync, 4:3 aspect ratio
# ModeLine "400x300"     18     400  416  448  512   300  301  602  312 Doublescan
# 400x300 @ 60 Hz, 37.8 kHz hsync
# Modeline "400x300"     20     400  416  480  528   300  301  303  314 Doublescan
# 400x300 @ 72 Hz, 48.0 kHz hsync
# Modeline "400x300"     25     400  424  488  520   300  319  322  333 Doublescan
# 480x300 @ 56 Hz, 35.2 kHz hsync, 8:5 aspect ratio
# ModeLine "480x300"     21.656 480  496  536  616   300  301  302  312 Doublescan
# 480x300 @ 60 Hz, 37.8 kHz hsync
# Modeline "480x300"     23.890 480  496  576  632   300  301  303  314 Doublescan
# 480x300 @ 63 Hz, 39.6 kHz hsync
# Modeline "480x300"     25     480  496  576  632   300  301  303  314 Doublescan
# 480x300 @ 72 Hz, 48.0 kHz hsync
# Modeline "480x300"     29.952 480  504  584  624   300  319  322  333 Doublescan

EndSection


# **********************************************************************
# Graphics device section
# **********************************************************************

# Any number of graphics device sections may be present

# Standard VGA Device:

Section "Device"
    Identifier	"Generic VGA"
    VendorName	"Unknown"
    BoardName	"Unknown"
    Chipset	"generic"

#    VideoRam	256

#    Clocks	25.2 28.3

EndSection

# Sample Device for accelerated server:

# Section "Device"
#    Identifier	"Actix GE32+ 2MB"
#    VendorName	"Actix"
#    BoardName	"GE32+"
#    Ramdac	"ATT20C490"
#    Dacspeed	110
#    Option	"dac_8_bit"
#    Clocks	 25.0  28.0  40.0   0.0  50.0  77.0  36.0  45.0
#    Clocks	130.0 120.0  80.0  31.0 110.0  65.0  75.0  94.0
# EndSection

# Device configured by xf86config:

Section "Device"
    Identifier  "Cirrus Logic GD542x"
    VendorName  "Unknown"
    BoardName   "Unknown"
    #VideoRam    4096
# Device section for Cirrus Logic GD5420/2/4/6/8/9-based cards.
    #MemBase 0x00e00000
    #MemBase 0x04e00000
    #Option "linear"
# Use Option "no_bitblt" if you have graphics problems. If that fails
# try Option "noaccel".
# Refer to /usr/X11R6/lib/doc/README.cirrus.
# To allow linear addressing, uncomment the Option line and the
# address that the card maps the framebuffer to.
    Clocks  25.23  28.32  41.16  36.08  31.50  39.99  45.08  49.87
    Clocks  64.98  72.16  75.00  80.01  85.23
EndSection


# **********************************************************************
# Screen sections
# **********************************************************************

# The Colour SVGA server

Section "Screen"
    Driver      "svga"
    # Use Device "Generic VGA" for Standard VGA 320x200x256
    #Device      "Generic VGA"
    Device      "Cirrus Logic GD542x"
    Monitor     "My Monitor"
    Subsection "Display"
        Depth       8
        # Omit the Modes line for the "Generic VGA" device
        Modes       "1024x768" "800x600" "640x480"
        ViewPort    0 0
        # Use Virtual 320 200 for Generic VGA
        # Virtual     1600 1280
    EndSubsection
    Subsection "Display"
        Depth       16
        Modes       "1024x768" "800x600" "640x480"
        ViewPort    0 0
        # Virtual     1600 1280
    EndSubsection
    Subsection "Display"
        Depth       32
        Modes       "1024x768" "800x600" "640x480"
        ViewPort    0 0
        # Virtual     1152 900
    EndSubsection
EndSection

# The 16-color VGA server

Section "Screen"
    Driver      "vga16"
    Device      "Generic VGA"
    Monitor     "My Monitor"
    Subsection "Display"
        Modes       "640x480" "800x600"
        ViewPort    0 0
        # Virtual     800 600
    EndSubsection
EndSection

# The Mono server

Section "Screen"
    Driver      "vga2"
    Device      "Generic VGA"
    Monitor     "My Monitor"
    Subsection "Display"
        Modes       "640x480" "800x600"
        ViewPort    0 0
        # Virtual     800 600
    EndSubsection
EndSection

# The accelerated servers (S3, Mach32, Mach8, 8514, P9000, AGX, W32, Mach64)

Section "Screen"
    Driver      "accel"
    Device      "Cirrus Logic GD542x"
    Monitor     "My Monitor"
    Subsection "Display"
        Depth       8
        Modes       "1024x768" "800x600" "640x480"
        ViewPort    0 0
        # Virtual     1600 1280
    EndSubsection
    Subsection "Display"
        Depth       16
        Modes       "1024x768" "800x600" "640x480"
        ViewPort    0 0
        # Virtual     1600 1280
    EndSubsection
    Subsection "Display"
        Depth       32
        Modes       "1024x768" "800x600" "640x480"
        ViewPort    0 0
        # Virtual     1152 900
    EndSubsection
EndSection
EOF

if [ "$XFREECFG" != "$XFREECFG_ETC" ]; then
  cp "$XFREECFG" "$XFREECFG_ETC"
fi

else
echo "No supported X11 server found."
fi

else
# Link to the correct X server
for SERVER in /usr/X386/bin/XF86_SVGA /usr/X386/bin/XF86_VGA16 /usr/X386/bin/XF86_mono /usr/X386/bin/X386mono; do
  if [ -f "$SERVER" ]; then
    echo "Found X11 server at $SERVER"
    (cd $(dirname "/$SERVER"); ln -sf $(basename "$SERVER") X)
    break
  fi
done

# if server is installed, configure
if [ -x "$SERVER" ]; then

# find the configuration directory
for X11PATH in /etc/X11 /var/X11/lib/X11 /usr/X386/lib/X11; do
  if [ -d "$X11PATH" ]; then
    break
  fi
done

echo "Creating Xconfig in $X11PATH"

if [ -f "$X11PATH/Xconfig" ]; then
    cp $X11PATH/Xconfig $X11PATH/Xconfig.orig
fi

# add first part of Xconfig
cat > $X11PATH/Xconfig <<EOF
# \$XFree86: mit/server/ddx/x386/Xconfig.cpp,v 2.0 1993/10/08 15:55:00 dawes Exp \$
# \$XConsortium: Xconfig,v 1.2 91/08/26 14:34:55 gildea Exp \$
#
# Copyright 1990,91 by Thomas Roell, Dinkelscherben, Germany.
# Copyright 1992,93 by David Dawes, David Wexelblat
#
# Permission to use, copy, modify, distribute, and sell this software 
# and its documentation for any purpose is hereby granted without fee, 
# provided that the above copyright notice appear in all copies and 
# that both that copyright notice and this permission notice appear in 
# supporting documentation, and that the names of the above listed authors 
# not be used in advertising or publicity pertaining to distribution of 
# the software without specific, written prior permission.  The above 
# listed authors make no representations about the suitability of this 
# software for any purpose.  It is provided "as is" without express or 
# implied warranty.
#
# THE ABOVE LISTED AUTHORS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS 
# SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND 
# FITNESS, IN NO EVENT SHALL THE ABOVE LISTED AUTHORS BE LIABLE FOR 
# ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER 
# RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF 
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN 
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Author:  Thomas Roell, roell@informatik.tu-muenchen.de
#
# Extensive modifications by the XFree86 Core Team

# **********************************************************************
# Refer to the Xconfig(4/5) man page for details about the format of 
# this file. This man page is installed as /usr/X386/man/man5/Xconfig.5x 
# **********************************************************************

# **********************************************************************
# Generic parameters section
# **********************************************************************

#
# some nice paths, to avoid conflicts with other X-servers
#
RGBPath		"/usr/X386/lib/X11/rgb"

#
# Multiple FontPath entries are allowed (which are concatenated together),
# as well as specifying multiple comma-separated entries in one FontPath
# command (or a combination of both methods)
#
FontPath	"/usr/X386/lib/X11/fonts/misc/"
FontPath	"/usr/X386/lib/X11/fonts/Type1/"
FontPath	"/usr/X386/lib/X11/fonts/Speedo/"
FontPath	"/usr/X386/lib/X11/fonts/75dpi/"
# FontPath	"/usr/X386/lib/X11/fonts/100dpi/"

#
# Uncomment this to cause a core dump at the spot where a signal is 
# received.  This may leave the console in an unusable state, but may
# provide a better stack trace in the core dump to aid in debugging
#
# NoTrapSignals

# **********************************************************************
# Input devices
# **********************************************************************

#
# Enable this to use the XQUEUE driver for keyboard and mouse handling
# under System V.  This may go away in the future.
#
# Note - If you use XQUEUE, you must comment out the keyboard and
#        mouse definitions.
#
# Xqueue

#
# Keyboard and various keyboard-related parameters
#
Keyboard
  AutoRepeat 500 5
  ServerNumLock
#  Xleds      1 2 3
#  DontZap
#
# To set the LeftAlt to Meta, RightAlt key to ModeShift, 
# RightCtl key to Compose, and ScrollLock key to ModeLock:
# 
#  LeftAlt     Meta
#  RightAlt    ModeShift
#  RightCtl    Compose
#  ScrollLock  ModeLock

#
# Mouse definition and related parameters
#
$MOUSETYPE	"/dev/$MOUSEDEV"
#  BaudRate	9600
#  SampleRate	150
  Emulate3Buttons

# **********************************************************************
# Graphics drivers
# **********************************************************************

#
# The 8-bit colour SVGA driver
#
VGA256
  Chipset   "clgd5422"
  # Virtual   1024 768
  Modes     "1024x768"
  Clocks	  25 40 65
EOF

# only add VGA16 section if the server exists
if [ -f /usr/X386/bin/XF86_VGA16 ]; then
cat >> "$X11PATH/Xconfig" <<EOF
# 
# The 16-colour VGA driver
#
VGA16
  # Virtual   800 600
  Modes     "800x600"
  Clocks    25 40 65
EOF
fi

# add the rest of the Xconfig file
cat >> "$X11PATH/Xconfig" <<EOF
#
# The 1-bit mono SVGA driver
#
VGA2
  # Virtual   800 600
  Modes	    "800x600"
  Clocks    25 40 65

#
# The Hercules driver.  For Hercules, the only valid configuration option
# is ScreenNo (refer to the manual page).
#
# HGA2

#
# The alternate monochrome driver.  Refer to the XF86_Mono manual page.
#
# BDM2

# 
# The accelerated servers (S3, Mach32, Mach8, 8514)
#
#ACCEL
#  Virtual   1024 768
#  Modes     "1024x768"

#
# For boards with a programmable clock generator, you use a line like:
#
# Clocks "icd2061a"

# **********************************************************************
# Database of video modes
# **********************************************************************
ModeDB
# name        clock   horizontal timing     vertical timing      flags
"640x480"     25      640  664  760  800    480  491  493  525
"800x600"     40      800  840  968 1056    600  601  605  628 +hsync +vsync
"1024x768"    65     1024 1032 1176 1344    768  771  777  806 -hsync -vsync
EOF

else
echo "No supported X11 server found."
fi

fi
