#!/bin/sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
while [ 0 ]; do
rm -f $TMP/SeTDS $TMP/SeTmount
cat << EOF > $TMP/tempmsg

OK, we will install from a directory within the current
filesystem. If you have mounted this directory yourself,
you should not use /mnt or /var/log/mount as mount points,
since Setup might need to use these directories.  You may
install from any part of the current directory structure,
no matter what the media is (including NFS). You will need
to type in the name of the directory containing the 
subdirectories for each source disk.

Which directory would you like to install from?
EOF
dialog --title "INSTALL FROM THE CURRENT FILESYSTEM" \
 --inputbox "`cat $TMP/tempmsg`" 19 67 2> $TMP/sourcedir
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/sourcedir $TMP/tempmsg
 exit
fi
SOURCEDIR="`cat $TMP/sourcedir`"
rm -f $TMP/sourcedir $TMP/tempmsg
rm -f /var/log/mount 2> /dev/null
rmdir /var/log/mount 2> /dev/null
ln -sf $SOURCEDIR /var/log/mount
if [ -d $SOURCEDIR ]; then
 echo "/var/log/mount" > $TMP/SeTDS
 echo "-source_mounted" > $TMP/SeTmount
 echo "/dev/null" > $TMP/SeTsource
 exit
else
 cat << EOF > $TMP/tempmsg

Sorry - the directory you specified is not valid. Please 
check the directory and try again.

(Directory given: $SOURCEDIR)

EOF
 dialog --title "INVALID DIRECTORY ENTERED" --msgbox "`cat $TMP/tempmsg`" 10 65
 rm -f $TMP/SeTDS $TMP/SeTmount $TMP/sourcedir $TMP/tempmsg
fi
done;
