#!/bin/sh
T_PX="`cat /tmp/SeTT_PX`"
rm -f /tmp/SeTSERIES
if [ "$T_PX" = "/" ]; then
 BASE=off
else
 BASE=on
fi
dialog --title "SERIES SELECTION" --checklist \
"\n\
Use the spacebar to select the disk sets you wish to install.\n\
You can use the UP/DOWN arrows to see all the possible choices.\n\
Press the ENTER key when you are finished. If you need to \n\
install a disk set that is not listed here, check the box for \n\
custom additional disk sets.\n" 20 75 7 \
"CUS" "Also prompt for CUSTOM disk sets" off \
"A" "Base Linux system" $BASE \
"AP" "Various Applications that do not need X" off \
"D" "Program Development (C, C++, Lisp, Perl, etc.)" off \
"E" "GNU Emacs" off \
"F" "FAQ lists, HOWTO documentation" off \
"I" "Info files readable with info, JED, or Emacs" off \
"IV" "InterViews Development + Doc and Idraw Apps for X" off \
"N" "Networking (TCP/IP, UUCP, Mail, News)" off \
"OOP" "Object Oriented Programming (GNU Smalltalk)" off \
"Q" "Extra Linux kernels with UMSDOS/non-SCSI CD drivers" off \
"T" "TeX" off \
"TCL" "Tcl/Tk/TclX, Tcl language, and Tk toolkit for X" off \
"X" "XFree-86 X Window System" off \
"XAP" "X Applications" off \
"XD" "XFree-86 X11 Server Development System" off \
"XV" "XView (OpenLook Window Manager, apps)" off \
"Y" "Games (that do not require X)" off 2> /tmp/series
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/series
 exit
fi
INSTSETS="`cat /tmp/series | tr -d " "`"
INSTSETS="`echo $INSTSETS | tr "\042" "#" `"
INSTSETS="`echo $INSTSETS | tr "," "#" `"
rm -f /tmp/series
TEST="`echo $INSTSETS | cut -b1-5`"
if [ "$TEST" = "#CUS#" ]; then
 INSTSETS="`echo $INSTSETS | cut -b5-`"
 dialog --title "CUSTOM DISK SETS" --inputbox "\n\
Please enter the names (such as X, Y, Z) of\n\
the custom disk sets that you would also\n\
like to install. Please do not re-enter the\n\
names of sets you have previously selected.\n" 13 55 2> /tmp/custom
 if [ $? = 1 -o $? = 255 ]; then
  rm -f /tmp/custom
  exit
 fi
 CUSTSETS="`cat /tmp/custom | tr " " "#" | tr "," "#"`"
 rm -f /tmp/custom
 INSTSETS="`echo $INSTSETS``echo $CUSTSETS`"
fi
echo "$INSTSETS" > /tmp/SeTSERIES
