#!/bin/sh
rm -f /tmp/SeTDS /tmp/SeTmount
cat << EOF > /tmp/tmpmsg

The base Slackware series (A) can be installed from 1.2M
or 1.44M media. Most of the other disks will not fit on 
1.2M media, but can be downloaded to your hard drive and 
installed from there later.

Which drive do you want to install from?
EOF
dialog --title "SELECT FLOPPY DRIVE" --menu "`cat /tmp/tmpmsg`" 18 67 4 \
"/dev/fd0u1440" "1.44M drive a:" \
"/dev/fd1u1440" "1.44M drive b:" \
"/dev/fd0h1200" "1.2M drive a:" \
"/dev/fd1h1200" "1.2M drive b:" 2> /tmp/whichdrv
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/whichdrv /tmp/tmpmsg
 exit
fi
rm -f /tmp/tmpmsg
mv /tmp/whichdrv /tmp/SeTsource
echo "" > /tmp/SeTDS
echo "" > /tmp/SeTmount
