[qemu]
profile = "linux-2.0"

[qemu.network]
device = "pcnet"

[download]
cdrom = "infomagic/ldr/1998_01"

[extract]
source = "disc1.iso"
boot_image = "images/boot.img"

[install]
driver = "redhat-newt"
variant = "5.0"

[install.locale]
hardware_clock = "utc"
timezone = "Etc/UTC"
keymap = "us"

[install.accounts]
root_password = "password"

[install.packages]
# Base is mandatory and is not shown in the component checklist.
components = [
  # "Printer Support",
  "X Window System",
  "Mail/WWW/News Tools",
  # "DOS/Windows Connectivity",
  "File Managers",
  # "Graphics Manipulation",
  # "X Games",
  # "Console Games",
  "X multimedia support",
  "Console Multimedia",
  # "Print Server",
  "Networked Workstation",
  "Dialup Workstation",
  # "News Server",
  # "NFS Server",
  # "SMB (Samba) Connectivity",
  # "IPX/Netware(tm) Connectivity",
  # "Anonymous FTP/Gopher Server",
  # "Web Server",
  # "DNS Name Server",
  # "Postgres (SQL) Server",
  # "Network Management Workstation",
  # "TeX Document Formatting",
  # "Emacs",
  # "Emacs with X windows",
  # "C Development",
  # "Development Libraries",
  # "C++ Development",
  # "X Development",
  # "Extra Documentation",
]

[postinst]
stages = ["x11"]

[postinst.x11]
chipset = "clgd5446"
